# Generated by Django 5.0.2 on 2024-02-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
